--- 
$schemaver: 1.1
name: petersonpest.github.io
type: web app
aliases:
short_description: peterson pest webpage
assignment_group: gro:ad-front end technologies and applications
notes: 
maintained_by:
  - ndpete
developed_by_byu: False
ddd:
  business_domain: 
  ubiquitous_language_url: 
  context_map_url: 
links:
  system_documentation_url: 
  source_repo_url: https://github.com/test-ndpete-org/petersonpest.github.io
  swagger_urls:
microservice: 
technologies_used:
  - HTML
  - CSS
  - JavaScript
stages:
  development:
    urls:
      product_page: http://petersonpest.github.io
      physical_url: 
      virtual_url: 
    hosting_location: other
    aws_account: 
    relationships: 
      depends_on:
        db_read_write:
        db_read_only:
        software:
          - github.com:production
      supports:
        software:
        service:
          - Google Apps - Free
      reverse_proxy: 
      runs_on:
        server_cluster:
        virtual_server:
        rack_server:
        blade_server:
tags:
  data-sensitivity: public
  env: development
  app: petersonpest.github.io
  team: ad:feta
federation_json_url: https://github.com/test-ndpete-org/petersonpest.github.io/.repo-meta.yml
x-anything: